/**
 * Unified contraction map shared by prompt-patterns and lexical-index.
 *
 * Merges both apostrophe and apostrophe-free forms so that every module
 * normalizing user text behaves identically.
 */
export const CONTRACTIONS: Record<string, string> = {
  "aren't": "are not",
  arent: "are not",
  "can't": "cannot",
  cant: "cannot",
  "couldn't": "could not",
  couldnt: "could not",
  "didn't": "did not",
  didnt: "did not",
  "doesn't": "does not",
  doesnt: "does not",
  "don't": "do not",
  dont: "do not",
  "hasn't": "has not",
  hasnt: "has not",
  "haven't": "have not",
  havent: "have not",
  "how's": "how is",
  "i'm": "i am",
  "i've": "i have",
  // apostrophe-free variants (casual typing)
  im: "i am",
  "isn't": "is not",
  isnt: "is not",
  "it'll": "it will",
  // apostrophe forms
  "it's": "it is",
  itll: "it will",
  ive: "i have",
  "let's": "let us",
  lets: "let us",
  "shouldn't": "should not",
  shouldnt: "should not",
  "that's": "that is",
  "there's": "there is",
  "they'll": "they will",
  "they're": "they are",
  "they've": "they have",
  theyll: "they will",
  theyre: "they are",
  theyve: "they have",
  "wasn't": "was not",
  wasnt: "was not",
  "we're": "we are",
  "we've": "we have",
  were: "we are",
  "weren't": "were not",
  werent: "were not",
  weve: "we have",
  "what's": "what is",
  "where's": "where is",
  "who'll": "who will",
  "who's": "who is",
  wholl: "who will",
  "won't": "will not",
  wont: "will not",
  "wouldn't": "would not",
  wouldnt: "would not",
  "you're": "you are",
  "you've": "you have",
  youre: "you are",
  youve: "you have",
};
